name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Sync & Build
        run: |
          go mod tidy
          go build -o bvm ./cmd/bvm/main.go
          zip bvm-linux.zip bvm

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: bvm-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
